#!/usr/bin/env sh

UNIT_CONFIGURATION_FILE="${UNIT_CONFIGURATION_FILE:?}"
UNIT_SOCKET="${UNIT_SOCKET:?}"

# Make sure that unit configuration file exists
if [ ! -f "${UNIT_CONFIGURATION_FILE}" ]; then
    echo "> Error: Configuration file '${UNIT_CONFIGURATION_FILE}' not found"
    sleep 5
    exit 1
fi

echo "> Unit configuration"
echo "  Configuration: ${UNIT_CONFIGURATION_FILE}"
echo "         Socket: ${UNIT_SOCKET}"
echo ""

# Keep polling for availability of unit socket
while [ ! -S "${UNIT_SOCKET}" ]; do
    echo "> Waiting for unitd socket to become available"
    sleep 0.5
done

# Keep polling until unit starts responding on the socket
until socat -u OPEN:/dev/null "UNIX-CONNECT:${UNIT_SOCKET}"; do
    echo "> Waiting for unitd socket to be ready"
    sleep 0.5
done

set -e
# Submit configuration to unit service
echo "> Sending configuration to unitd"
curl -X PUT --data-binary "@${UNIT_CONFIGURATION_FILE}" --unix-socket "${UNIT_SOCKET}" http://localhost/config/
echo "> Done"

sleep infinity
