#!/command/with-contenv bash
# shellcheck shell=bash

# init-docker-secrets main
main() {
    # This will prepend service name to all output from here
    exec > >(while read -r line; do echo "[init-docker-secrets] ${line}"; done) 2>&1

    echo "Error: init-docker-secrets is not implemented yet. See Dockerfile > rootfs for more information."
}
main
