#!/command/with-contenv bash
# shellcheck shell=bash

# init-unitd-configure main
main() {
    # This will prepend service name to all output from here
    exec > >(while read line; do echo "[init-unitd-configure] ${line}"; done) 2>&1

    local unitConfigurationFile="${UNIT_CONFIGURATION_FILE:?}"
    local unitSocket="${UNIT_SOCKET:?}"

    # Make sure that unit configuration file exists
    if [ ! -f "${unitConfigurationFile}" ]; then
        echo "Error: Configuration file '${unitConfigurationFile}' not found"
        sleep 5
        return 1
    fi

    echo "Unit configuration"
    echo " Configuration: ${unitConfigurationFile}"
    echo "        Socket: ${unitSocket}"
    echo ""

    # Keep polling for availability of unit socket
    while [ ! -S "${unitSocket}" ]; do
        echo "Waiting for unitd socket to become available..."
        sleep 0.5
    done

    # Keep polling until unit starts responding on the socket
    until socat -u OPEN:/dev/null "UNIX-CONNECT:${unitSocket}"; do
        echo "Waiting for unitd socket to be ready..."
        sleep 0.5
    done

    set -e

    echo "Sending configuration to unitd"
    unitctl "${unitConfigurationFile}"

    echo "Done"
}

main
